version: '3.8'
services:
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db/taskdb
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=taskdb
    ports:
      - "5432:5432"
